### ISSUE TITLE
Login failed with `Unexpected string in JSON at position 250`

### ISSUE THREAD

**Issue by shouldsee** [jks-liu/WPL-s#12]
感觉是不是读了Zhihu-vscode的啥文件然后parse error了?我这里装的是压缩后的js所以查不到源代码行

```
Http error SyntaxError: Unexpected string in JSON at position 250
	at JSON.parse (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2582811
	at new c (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2582959)
	at l (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2692381)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2692643
	at l.<anonymous> (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2709639)
	at Generator.next (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2709109
	at new Promise (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2708854
	at l.sendRequest (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2709360)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2710468
	at Object.<anonymous> (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2696110)
	at Generator.next (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2695739
	at new Promise (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2695484
	at Object.isAuthenticated (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2696042)
	at Object.<anonymous> (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2697280)
	at Generator.next (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2696671
	at new Promise (<anonymous>)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2696416
	at Object.login (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2697217)
	at /home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/dist/extension.js:2:2689904
	at m._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30760)
	at m.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:31302)
	at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
	at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at Socket.P (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/lib/events.js:390:28)
	at addChunk (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/lib/internal/streams/readable.js:315:12)
	at readableAddChunk (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/lib/internal/streams/readable.js:289:9)
	at Socket.push (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/lib/internal/streams/readable.js:228:10)
	at Pipe.onStreamRead (/home/shouldsee/.vscode/extensions/jks-liu.wpls-1.5.0/lib/internal/stream_base_commons.js:199:23)
	at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {stack: 'SyntaxError: Unexpected string in JSON at pos…Trampoline (node:internal/async_hooks:130:17)', message: 'Unexpected string in JSON at position 250'}

```

**Comment by jks-liu** [comment]
有能复现的Markdown文件吗？

**Comment by shouldsee** [comment]
> 有能复现的Markdown文件吗？

Did not keep one. Is the marketplace version the latest one?

**Comment by jks-liu** [comment]
Marketplace latest version is corresponding to Github latest version.
